"""Markdown report rendering for scan results and evaluation runs."""
from __future__ import annotations

from .checklist import ChecklistResult
from .scanner import ScanResult, VULN_CLASSES


def render_markdown(scan: ScanResult, checklist: ChecklistResult,
                    run_reports=None) -> str:
    lines = []
    ap = lines.append

    ap("# BenchShield Audit Report")
    ap("")
    ap(f"- **Target**: `{scan.root}`")
    ap(f"- **Files scanned**: {scan.files_scanned}")
    counts = scan.severity_counts
    ap(f"- **Findings**: {len(scan.findings)} "
       f"(critical {counts['critical']} / high {counts['high']} / "
       f"medium {counts['medium']} / info {counts['info']})")
    ap("")

    ap("## Findings")
    ap("")
    if not scan.findings:
        ap("No vulnerability patterns detected. "
           "(Heuristic scan - see Limitations in the README.)")
    for f in scan.sorted_findings():
        ap(f"### [{f.severity.upper()}] {f.vuln_class} · {f.rule} — {f.title}")
        ap("")
        ap(f"- **File**: `{f.file}:{f.line}`")
        if f.evidence:
            ap(f"- **Evidence**: `{f.evidence}`")
        ap(f"- **Pattern**: {VULN_CLASSES.get(f.vuln_class, f.vuln_class)}")
        if f.remediation:
            ap(f"- **Fix**: {f.remediation}")
        ap("")

    ap("## Agent-Eval Checklist")
    ap("")
    ap("| # | Requirement | Status | Details |")
    ap("|---|---|---|---|")
    for cid, title, status, details in checklist.items:
        ap(f"| {cid} | {title} | {status.upper()} | {details} |")
    ap("")
    ap(f"**Grade: {checklist.grade}**")
    ap("")

    if run_reports:
        ap("## Evaluation runs")
        ap("")
        ap("| Runner | Agent | Solved | Rate |")
        ap("|---|---|---|---|")
        for rep in run_reports:
            ap(f"| {rep.runner} | {rep.agent} | {rep.solved_count}/{rep.total} "
               f"| {rep.rate * 100:.0f}% |")
        ap("")

    ap("---")
    ap("Generated by [BenchShield](https://github.com/) - heuristic audit for "
       "agent benchmark integrity. Findings require human review.")
    return "\n".join(lines)
